name = "GeoEstimation"
uuid = "a4aa24f8-9f24-4d1a-b848-66d123bfa54d"
authors = ["JÃºlio Hoffimann <julio.hoffimann@gmail.com> and contributors"]
version = "0.5.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Distances = "0.9, 0.10"
GeoStatsBase = "0.18"
Meshes = "0.10"
NearestNeighbors = "0.4"
StaticArrays = "0.12, 1.0"
julia = "1.5"
